#!/usr/bin/env bash

TRACKER_FILE=~/work-tracker.txt
function track() {
  echo "$1, $(date)" >> $TRACKER_FILE
  stamp=$(cat $TRACKER_FILE | tail -n 1)
  echo "Appended $stamp to $TRACKER_FILE"
}

function workweek() {
  if [ -d ".git" ]; then
    count=$(git log --oneline --since="1 week ago" | wc -l | xargs)
    echo "Stats since 1 week ago"
    git diff HEAD~$count --shortstat
  else
    echo "Not a git directory"
    exit 1
  fi
}


function optimize_workflow() {
  history                           | \
    awk '{print $4 " " $5}'         | \
    awk 'BEGIN {FS="|"} {print $1}' | \
    sort                            | \
    uniq -c                         | \
    sort -rn                        | \
    head -30
}

function dev() {
  track $1
  cd "$HOME/dev/$1"
}

alias oss='dev oss'

function nom() {
  set -x
  rm -rf node_modules tmp
  npm i
  set +x
}

function bom(){
  set -x
  rm -rf bower_components;
  bower cache clean
  bower i
  set +x
}

function bigdir() {
  du -hsx * | sort -r | head -10
}

function webshare() {
  PORT=8000
  echo "Starting webserver on $PORT"
  python -m SimpleHTTPServer
}

## Shortcuts
alias ls='ls -alHpGh'
alias be='bundle exec'
alias grep='grep -i --color'
alias egrep='egrep -i --color'
alias rc='rustc'
alias ow=optimize_workflow
alias ww=workweek
alias vup='vim +PluginInstall +qall'
alias vi=vim
alias tmux='TERM=screen-256color-bce tmux'
alias nombom='nom && bom'
alias dc='docker-compose'
alias dm='docker-machine'

########### START Python ##################
alias pd='python setup.py sdist'
alias pup='python setup.py sdist upload'
alias pst='python setup.py test'

function pip-cd {
  USAGE="Usage: pip-show <pacakgename>"
  if [ -z $1  ]; then
    echo $USAGE
    return 1
  fi

  location=$(pip show $1 | grep Location | awk '{ print $2 }')
  if [ -z $location ]; then
    echo "$1 not found"
    echo $USAGE
    return 1
  fi

  echo "$location"
  cd $location/$1
}

function v() {
  name="${1-env}"

  if [ "$name" ==  "off" ]; then
    deactivate
    return $?
  fi

  echo "Activating $name"
  virtualenv $name > /dev/null
  source "$name/bin/activate"
}

alias f='flake8'

function flist() {
  flake8 | awk '{print $2}' | sort -u
}

function fl {
  flake8 --select $1
}
############ END Python ##################

# Git shortcuts
alias gp='git push origin'
alias gpf='git push --force-with-lease'
alias gc='git commit'
alias gaa='git add -A'
alias gpa='for r in $(git remote); do; echo "--> Pushing to $r"; git push $r; done'
alias gpu='git push upstream'

# middleman
alias ms='bundle exec middleman server'
alias md='bundle exec middleman build'

# ember
alias es='ember server'

# Capistrano
alias cpu='cap uat deploy'
alias cpp='cap production deploy'

# General
alias e='code'
alias b='brew'
alias bu='b upgrade'
alias secs='date +%s'
