#!/usr/bin/env bash
#
# Setup PATH variable
# Source this in whatever shell profile

PATH=$PATH:$HOME/bin
PATH=$PATH:/usr/local/sbin                      # hombrew formulae
PATH=$PATH:$GOPATH/bin                          # Go
PATH=/usr/local/Cellar/python/2.7.6/bin:$PATH   # Python
PATH=$PATH:$HOME/.rvm/bin                       # Ruby
PATH=$PATH:/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin   # swiftc
PATH="$PATH:$(brew --prefix homebrew/php/php56)/bin" # PHP https://github.com/Homebrew/homebrew-php
PATH=$PATH:/usr/local/lib/python2.7/site-packages # Python packages

export PATH
