#!/usr/bin/env bash
#
# Setup PATH variable
# Source this in whatever shell profile

PATH=$PATH:$HOME/bin
PATH=$PATH:/usr/local/sbin                                                  # Homebrew formulae
PATH=$PATH:$GOPATH/bin                                                      # Go
PATH=/usr/local/Cellar/python/2.7.6/bin:$PATH                               # Python
PATH=$PATH:/usr/local/lib/python2.7/site-packages                           # Python packages
PATH=$PATH:/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin   # swiftc
PATH="/Users/mehulkar/perl5/bin${PATH+:}${PATH}"                            # Perl
PATH="$PATH:$HOME/.rvm/bin"                                                 # Ruby
PATH="$PATH:$VOLTA_HOME/bin"

export PATH

